Back end
Chewyfitz/comp30022-it-project pull request #38
Opened 2019-10-24 07:41 UTC by Chewyfitz

Merging Back-end into a dev branch for master to combine with the front-end branch so we can merge into master with no conflicts

2019-10-24 11:57 UTC, PCA000 requested changes
Please don't use require('firebase') which includes the entire firebase SKD. Instead include only the individual SDKs you need. This doesn't change the correctness of your code, but if this is going into production then this is not efficient.

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/album.js
> +	const position = req.params.position;
I don't know much about routes, but should "req.params.position" be "req.query.position"

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/album.js
> +		template = pageUtil.getAlbumPageTemplate(user, req.params.albumId, req.params.pageId);
What happens if this returns undefined? Should you then return the albums default template?

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/album.js
>  });
Is this the same as routes.patch (('/:albumId/:pageId') for a reason?

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/image.js
>  	// Get a specific image's direct url
is view a needed param?

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/image.js
>  	// Get a specific image's direct url
To clarify, because it's currently unused, if this this route was called without a view param, would it still work?

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/image.js
> +		imageId = req.query.photoId;
Is it possible that photoId is in both params and query? If so, what intended functionality should it have? Would the front end expect both of them deleted?

2019-10-24 11:57 UTC, PCA000 commented on back-end/routes/user.js
> +	if(req.params.code && req.query.password){
do you want req.query.password or req.params.password? (I'm only asking because it looks like passsword it a param)

2019-10-24 11:57 UTC, PCA000 commented on back-end/util/albumPage.js
> +    return await database.getAlbumPageData(user, album, page);
The function name suggests you may want to call database.getAlbumPageTemplate instead.

2019-10-24 11:57 UTC, PCA000 commented on back-end/util/auth.js
> +const firebase = require('firebase');
This includes the entire firebase SDK which is not recommended for production builds.

2019-10-24 12:01 UTC, PCA000 commented on back-end/util/image.js
> +async function addPhotoToUser(user, image, album = undefined, photoDateTime = null){
should probably include height and width

2019-10-24 12:41 UTC, PCA000 requested changes
Update the arguments of database.addPhoto(user, image, photoDateTime) to database.addPhoto(user, image, height, width. photoDateTime) on line 75 of util/image.js

2019-10-24 12:41 UTC, PCA000 commented on back-end/util/image.js
> +    var albumPosition = await database.addPhoto(user, image, photoDateTime).then((success) => {
database.addPhoto(user, image, photoDateTime) needs to be database.addPhoto(user, image, height, width, photoDateTime), even if height and width are undefined otherwise photoDateTime will be added in the height field.

2019-10-24 12:41 UTC, PCA000 commented on back-end/util/image.js
> +    photoData = await database.getPhotoData(user, imageId);
You might like to use getPhotoReference(user, imageId) instead

2019-10-24 12:41 UTC, PCA000 commented on back-end/util/user.js
> +const firebase = require('firebase');
shouldn't be used in a production app

2019-10-24 15:22 UTC, PCA000 commented on back-end/routes/album.js
> +	const position = req.params.position;
looks like it got fixed in 9caa841

2019-10-24 15:44 UTC, PCA000 commented on back-end/routes/album.js
>  });
1). Patch route not used
2). Partially an artefact of Album Page only storing template

2019-10-24 15:50 UTC, PCA000 commented on back-end/routes/album.js
> +		template = pageUtil.getAlbumPageTemplate(user, req.params.albumId, req.params.pageId);
Resolved in #43 if I've coded the route logic correctly.

2019-10-24 15:54 UTC, PCA000 commented on back-end/util/auth.js
> +const firebase = require('firebase');
Should be resolved by #43, or it might be totally broken by #43

2019-10-24 15:58 UTC, PCA000 commented on back-end/util/image.js
> +async function addPhotoToUser(user, image, album = undefined, photoDateTime = null){
Resolved by #43

2019-10-24 15:59 UTC, PCA000 commented on back-end/util/user.js
> +const firebase = require('firebase');
Should be resolved by #43, or it might be totally broken by #43

2019-10-24 17:35 UTC, PCA000 commented on back-end/util/image.js
> +    var albumPosition = await database.addPhoto(user, image, photoDateTime).then((success) => {
Resolved by #43.

2019-10-26 10:01 UTC, Chewyfitz commented on back-end/routes/image.js
>  	// Get a specific image's direct url
ah, view isn't a param, it's a part of the route. so if you go to [API_URL]/api/image/[imageId]/view it will give you _just the URL_ of the provided image ID.  
This way it's possible to render an image (or simply view an image) without needing to get all of the associated data. (a reasonably small saving, but it might become useful if images have long descriptions added to them.)

2019-10-26 10:04 UTC, Chewyfitz commented on back-end/routes/image.js
> +		imageId = req.query.photoId;
That's a good point, but this is just here to allow the photo to be deleted using either of the provided options (a part of the request url `DELETE [API_URL]/api/image/[imageId]` or as a query value `DELETE [API_URL]/api/image?imageId=[imageId]`)

2019-10-26 10:09 UTC, Chewyfitz commented on back-end/routes/user.js
> +	if(req.params.code && req.query.password){
The comment here is a bit misleading as I'm pretty sure it's a copy-paste from the above and refers to functionality we haven't implemented yet.  
  
Basically the `code` which is passed in as a param is verified with `firebase-auth` as a part of the password reset process  
(send an email -> get an email with a code -> come back to change your password with the code you just got in your email).  
In practice we're able to use firebase's default password reset form, so we don't actually need to use this until a more customised password reset system is implemented.

2019-10-26 10:11 UTC, Chewyfitz commented on back-end/util/albumPage.js
> +    return await database.getAlbumPageData(user, album, page);
From memory this function was added early on, but yes `database.getAlbumPageTemplate` is probably the more expected function call in this instance.

2019-10-26 10:13 UTC, Chewyfitz commented on back-end/util/auth.js
> +const firebase = require('firebase');
If possible (as noted in #43 ) I'd like you to test this before it gets merged into the back-end branch.  
It would be great (and I'm 100% in support) if we can import only the authentication part of firebase, but if it requires some other functionality and causes the route to break it might have to stay like this.

2019-10-28 03:08 UTC, PCA000 commented on back-end/routes/image.js
>  	// Get a specific image's direct url
Ok, cool. That makes a lot more sense!

2019-10-28 03:16 UTC, PCA000 commented on back-end/routes/user.js
> +	if(req.params.code && req.query.password){
After reading the response to the comment on router.get('/:imageId/view', (req, res), I think it is actually the case where I thought password was a param because it was in the url, but it doesn't have a : in front of it so it's not actually a param right?

2019-10-28 03:17 UTC, PCA000 commented on back-end/util/auth.js
> +const firebase = require('firebase');
sure, I'll see if I can get the test code running on my end and come back with a verdict.

2019-10-28 03:36 UTC, Chewyfitz commented on back-end/routes/user.js
> +	if(req.params.code && req.query.password){
Yep, that's correct

2019-10-28 04:00 UTC, Chewyfitz commented on back-end/util/auth.js
> +const firebase = require('firebase');
I've also left a suggestion for how to fix it, since as far as I could tell it doesn't work https://github.com/Chewyfitz/comp30022-it-project/pull/43#discussion_r339330612

2019-10-29 08:00 UTC, PCA000 commented on back-end/util/auth.js
> +const firebase = require('firebase');
I've since changed how I've done the requirements and did some rudimentary tests on them to make sure they are actually usable this time. If there's any issues, I would suggest reverting this change and leaving it as including the entire firebase skd as it's not really worth putting any more time into it.

2019-10-29 08:01 UTC, PCA000 approved these changes

2019-10-29 09:13 UTC, Chewyfitz commented on back-end/util/image.js
> +    photoData = await database.getPhotoData(user, imageId);
Created an issue for this (#49)

2019-10-29 17:11 UTC, Chewyfitz commented on back-end/database.js
> +async function getSomeAlbumPhotos(userID, albumID, start=undefined, end=undefined) {
Seems like [this](https://firebase.google.com/docs/database/web/lists-of-data#filtering_data) might be a better way of dealing with getting set amounts of documents from a collection.
It might be worth exploring this since I imagine it would vastly reduce database use, since currently the 
`query.getNumDocsInCollection()` function (as far as I can tell) gets all of the data from a database collection and then simply returns its size.

2019-11-03 22:30 UTC, PCA000 commented on back-end/database.js
> +async function getSomeAlbumPhotos(userID, albumID, start=undefined, end=undefined) {
I agree about query.getNumDocsInCollection() behaviour, but in theory it's only being called if end is undefined (in which case get all should probably be called). It might pay looking into for the getAll function though. (It may be to late for me to do this as I don't think I'll be best a library until Thursday). It will also be interesting to see if they actually work on the keys, because the threads I was reading said you couldn't query on keys.

2019-11-04 06:59 UTC, Chewyfitz commented on back-end/database.js
> +async function getSomeAlbumPhotos(userID, albumID, start=undefined, end=undefined) {
Created an issue for this (#58) so it can be discussed further if needed and kept track of (though I imagine if I continue with this project I'll be taking over responsibility anyway)..

2019-11-04 07:00 UTC, merged